package Ventanas;



import Dibujos.Nave;
import Dibujos.Dibujable;
import Dibujos.BalaGrafica;
import Dibujos.Bala;
import Dibujos.Coordenadas;
import Dibujos.NaveGrafica;
import Dibujos.Panel;
import Dibujos.Ventana;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;

public class Interfaz extends javax.swing.JFrame {
    boolean estado=true;
    boolean estado2=true;

    public boolean isEstado2() {
        return estado2;
    }

    public void setEstado2(boolean estado2) {
        this.estado2 = estado2;
    }
   

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);                                       //para que aparescan al centro
    }
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Usuario.png"));
        return retValue;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Boton_Salir = new javax.swing.JButton();
        Boton_Jugar = new javax.swing.JButton();
        Boton_Opciones = new javax.swing.JButton();
        Boton_Records = new javax.swing.JButton();
        JLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(204, 204, 204));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("AirWar");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 990, 70));

        Boton_Salir.setBackground(new java.awt.Color(0, 102, 153));
        Boton_Salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton_Salir.setForeground(new java.awt.Color(204, 204, 204));
        Boton_Salir.setText("Salir");
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 90, 40));

        Boton_Jugar.setBackground(new java.awt.Color(0, 102, 153));
        Boton_Jugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton_Jugar.setForeground(new java.awt.Color(204, 204, 204));
        Boton_Jugar.setText("Jugar");
        Boton_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_JugarActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 300, 50));

        Boton_Opciones.setBackground(new java.awt.Color(0, 102, 153));
        Boton_Opciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton_Opciones.setForeground(new java.awt.Color(204, 204, 204));
        Boton_Opciones.setText("Opciones");
        Boton_Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_OpcionesActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 300, 50));

        Boton_Records.setBackground(new java.awt.Color(0, 102, 153));
        Boton_Records.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton_Records.setForeground(new java.awt.Color(204, 204, 204));
        Boton_Records.setText("Records");
        Boton_Records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RecordsActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Records, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 300, 50));

        JLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oiLHQw (1).jpg"))); // NOI18N
        JLabelFondo.setText("jLabel1");
        getContentPane().add(JLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 1040, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void Boton_OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_OpcionesActionPerformed
        this.setVisible(false);
        this.setEstado2(false);
        
    }//GEN-LAST:event_Boton_OpcionesActionPerformed

    private void Boton_RecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RecordsActionPerformed
        Interfaz_Records VentanaRecords = new Interfaz_Records(this);
        VentanaRecords.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_Boton_RecordsActionPerformed

    private void Boton_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_JugarActionPerformed
        this.setVisible(false);
        this.setEstado(false);
    }//GEN-LAST:event_Boton_JugarActionPerformed

   public static void main(String[] args) {
            EventQueue.invokeLater(new Runnable(){
            public void run(){
               new Interfaz().setVisible(true);
                   }
            });
        }
           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Jugar;
    private javax.swing.JButton Boton_Opciones;
    private javax.swing.JButton Boton_Records;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JLabel JLabelFondo;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
