
package Ventanas;

import Dibujos.Coordenadas;
import Dibujos.NaveGrafica;
import Dibujos.Panel;
import Dibujos.Ventana;
import Ejecuciones.Main;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import Dibujos.*;																				//Poder acceder a las clases dentro de dibujos
import Dibujos.Panel;
import java.awt.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;





public class Interfaz_Juego extends javax.swing.JFrame {
    boolean estado=true;
    boolean estado2=true;
    public String nombre;
   
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz_Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Usuario.png"));
        return retValue;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Boton_Volver = new javax.swing.JButton();
        Jugar = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        JLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(204, 204, 204));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Introduzca su nombre");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 990, 70));

        Boton_Volver.setBackground(new java.awt.Color(0, 102, 153));
        Boton_Volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton_Volver.setForeground(new java.awt.Color(204, 204, 204));
        Boton_Volver.setText("Volver");
        Boton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 90, 40));

        Jugar.setBackground(new java.awt.Color(0, 102, 153));
        Jugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jugar.setForeground(new java.awt.Color(204, 204, 204));
        Jugar.setText("Jugar");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        getContentPane().add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 300, 50));

        Nombre.setText("Nombre");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 420, 40));

        JLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oiLHQw (1).jpg"))); // NOI18N
        JLabelFondo.setText("jLabel1");
        getContentPane().add(JLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1040, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VolverActionPerformed
        this.setVisible(false);
        this.setEstado(false);
        this.setEstado2(false);
        
    }//GEN-LAST:event_Boton_VolverActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        nombre=Nombre.getText();
        this.setEstado(false);
        this.setVisible(false);
      
    }//GEN-LAST:event_JugarActionPerformed
    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
    public boolean isEstado2() {
        return estado2;
    }

    public void setEstado2(boolean estado2) {
        this.estado2 = estado2;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JLabel JLabelFondo;
    private javax.swing.JButton Jugar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables

}